services:
  mostlylucid:
    image: mostlylucid
    build:
      context: .
      dockerfile: Mostlylucid/Dockerfile
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    env_file:
      - .env