global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aspnetapp'
    metrics_path: /metrics
    scheme: https                 # Use HTTPS instead of HTTP
    static_configs:
      - targets: ['host.docker.internal:7240']  # Your HTTPS target
    tls_config:
      insecure_skip_verify: true  # Skip SSL verification (for self-signed certificates)