<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>f465224e-fbdc-4c99-8c3e-f31f3fc84670</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
      <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
      <PackageReference Include="Serilog" Version="4.4.0" />
      <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
      <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
      <PackageReference Include="Serilog.Exceptions.EntityFrameworkCore" Version="8.4.0" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="SerilogTracing" Version="2.4.0" />
      <PackageReference Include="SerilogTracing.Expressions" Version="2.4.0" />
      <PackageReference Include="SerilogTracing.Instrumentation.AspNetCore" Version="2.4.0" />
      <PackageReference Include="Scalar.AspNetCore" Version="1.2.60" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mostlylucid.DbContext\Mostlylucid.DbContext.csproj" />
      <ProjectReference Include="..\Mostlylucid.Services\Mostlylucid.Services.csproj" />
      <ProjectReference Include="..\Mostlylucid.Shared\Mostlylucid.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\js\site.js" />
      <_ContentIncludedByDefault Remove="wwwroot\favicon.ico" />
    </ItemGroup>

</Project>
