name: Publish Umami.NET

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the action for any tag that matches the pattern v1.0.0, v2.1.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # Specify the .NET version you need

      - name: Restore dependencies
        run: dotnet restore ./Umami.Net/Umami.Net.csproj

      - name: Build project
        run: dotnet build --configuration Release ./Umami.Net/Umami.Net.csproj --no-restore

      - name: Run tests
        run: dotnet test --configuration Release ./Umami.Net.Test/Umami.Net.Test.csproj --no-build --verbosity normal

      - name: Pack project
        run: dotnet pack --configuration Release ./Umami.Net/Umami.Net.csproj --no-build --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.UMAMI_NUGET_API_KEY }}
        env:
          NUGET_API_KEY: ${{ secrets.UMAMI_NUGET_API_KEY }}